import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const root = process.cwd();
const dist = join(root, 'dist');
if (!existsSync(join(dist, 'index.html'))) {
  throw new Error('dist/index.html is missing; run pnpm run build first');
}
const assetDir = join(dist, 'assets');
const jsFiles = readdirSync(assetDir).filter((file) => file.endsWith('.js'));
if (jsFiles.length === 0) {
  throw new Error('dist/assets contains no built JavaScript bundle');
}
const bundleText = jsFiles.map((file) => readFileSync(join(assetDir, file), 'utf8')).join('\n');
for (const expected of [
  'ASHA Studio',
  'studio-layout-root',
  'studio-menu-top-bar',
  'studio-left-scene-hierarchy-panel',
  'studio-viewport-top-bar',
  'studio-viewport-scene-panel',
  'studio-bottom-assets-panel',
  'studio-right-inspector-panel',
  'studio-editor-app-status-bar',
  'studio-editor-left-scene-hierarchy-dock',
  'studio-editor-central-viewport-dock',
  'studio-editor-right-inspector-dock',
  'studio-editor-bottom-command-evidence-dock',
  'runtime bridge:',
  'deferred',
  'native / Agora / GPU: not claimed',
  'boundary: public package roots only',
  'Scene / Hierarchy',
  'studio-scene-hierarchy-dock',
  'scene-hierarchy-tree-readout',
  'Selected voxel',
  'Preview ghost',
  'authority-backed',
  'preview-only',
  'State legend',
  'Scenario / Session',
  'Viewport — terrain-test-grid',
  'studio-central-reference-viewport-canvas',
  'studio-real-browser-3d-viewport-host',
  'studio-3d-webgl-canvas',
  'viewport-axis-gizmo',
  'viewport_3d_readback',
  'three_local_browser_projection',
  'selected-voxel:0,0,0',
  'preview-ghost:1,0,0',
  'applied-voxel:1,0,0',
  'viewport_camera_tool_interaction_proof',
  'viewport-camera-tool-readout',
  'viewport-scripted-actions-readout',
  'gui.frame_selected_target',
  'agent.select_visible_voxel',
  'gui.toggle_preview_ghost',
  'camera_tool_stale_readback_guard',
  'viewport_pick_hit_test_evidence',
  'pick:selected-voxel-center',
  'pick:background-no-hit',
  'pick_hit_stale_readback_guard',
  'viewport_visual_delta_crop_proof',
  'visual-delta:selected-before-crop',
  'visual-delta:applied-after-crop',
  'visual_delta_stale_readback_guard',
  'demo-asset-loaded-renderable',
  'Demo Asset Load (scene.load_asset)',
  'viewport-demo-asset-load-readout',
  'demo-asset-load-provenance',
  'studio-entity-browser-dock',
  'Entity Browser',
  'entity-browser-tree-readout',
  'entity-browser-selection-sync-readout',
  'selection.set_active_entity',
  'shading: Three.js local browser projection',
  'Viewport Editor Panel',
  'Command Palette / Menu Mirror',
  'Command Timeline',
  'Inspector / Readout',
  'Inspector / Readout',
  'studio-selected-target-inspector',
  'selected-target-preview-card',
  'selected-target-applied-card',
  'Proposed by Studio (TS), projection only.',
  'Validated by Authority (Rust), authoritative state.',
  'Authority transition',
  'Render projection',
  'software_snapshot_reference',
  'no native runtime, Agora, GPU, or performance claim',
  'Evidence / Export',
  'Command Timeline / Evidence Log',
  'Evidence / Artifacts',
  'bottom-command-row-list',
  'bottom-evidence-artifact-list',
  'artifact-review-export-0001',
  'artifact-agent-readout-0001',
  'not a second private command log',
  'asha_studio_shell',
  'visualId',
  'visualRole',
  'export_review_artifact_button',
  'run_proof_button',
  'scene_hierarchy',
  'central_3d_viewport',
  'selected_target_inspector',
  'command_evidence_dock',
  'command_timeline',
  'evidence_dock',
  'runtime_bridge_marker',
  'viewport_runtime_bridge_authority',
  'no_agora_gpu_native_claim_limitation',
  'selection_outline',
  'preview_ghost',
  'axis_gizmo',
  'applied_state_renderable',
  'visualContract',
  'authority.voxel.apply_brush',
]) {
  if (!bundleText.includes(expected)) {
    throw new Error(`built bundle is missing expected studio shell marker: ${expected}`);
  }
}
console.log(`asha-studio static smoke: OK (${jsFiles.length} JS bundle file(s))`);
